# Base configs
baseurl: /astral

# UI configs
title: "Rohan Takke"
name: "Rohan Takke"
bio: "A Pythonista|upcoming cyber security expert|currently learning raspberry pi"
social_urls:
  facebook: "https://www.facebook.com/profile.php?id=100007608408819&ref=br_rs"
  twitter: "https://www.twitter.com/https://twitter.com/takkerohan97"
  instagram: "https://www.instagram.com/_roh_26_07"
  
